---
service: journal-api
frameworkVersion: ">=1.28.0 <2.0.0"

plugins:
  - serverless-dynamodb-local
provider:
  name: aws
  runtime: go1.x
  stage: production
  versionFunctions: false
  timeout: 6
  memorySize: 128
  region: us-west-2

  iamRoleStatements:
    - Effect: "Allow"
      Resource: "*"
      Action:
        - "dynamodb:*"

package:
  individually: true

functions:
  handle_twilio_webhook:
    handler: /handle_twilio_webhook
    package: {artifact: bin/handle_twilio_webhook.zip}
    events:
      - http:
          path: twilio
          method: post
          cors: true

  insert_entry:
    handler: /insert_entry
    package: {artifact: bin/insert_entry.zip}
    events:
      - http:
          path: entry
          method: post
          cors: true

  get_entry:
    handler: /get_entry
    package: {artifact: bin/get_entry.zip}
    events:
      - http:
          path: entry/{entry_id}
          method: get
          cors: true
