---
service: journal-app
frameworkVersion: ">=1.28.0 <2.0.0"

plugins:
  - serverless-dynamodb-local
provider:
  name: aws
  runtime: go1.x
  region: us-west-2

  environment:
    AWS_ACCESS_KEY_ID: DEFAULT_ACCESS_KEY
    AWS_SECRET_ACCESS_KEY: DEFAULT_SECRET

resources:  # CloudFormation template syntax
  Resources:
    journal:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: journal
        AttributeDefinitions:
          - AttributeName: journal_id
            AttributeType: S
        KeySchema:
          - AttributeName: journal_id
            KeyType: HASH
        ProvisionedThroughput:
          ReadCapacityUnits: 1
          WriteCapacityUnits: 1

custom:
  dynamodb:
    stages:
      - dev
    start:
      host: localhost  # or the name of your Dynamo docker container
      port: "8000"  # the port of our Dynamo docker container
      noStart: true
      migrate: true
